### ISSUE TITLE
Handle the secret better

### ISSUE THREAD

**Issue by jutkko** [jutkko/copy-pasta#1]
The exported environment variables are only temporary, think of a better way to handle it!

**Comment by jutkko** [comment]
Having a set of default ones if certain env is not set is an option.

**Comment by vlad-stoian** [comment]
I started disliking environment variables as a source of information, since it seems like magic where and when those get set, and where they get used. I would rather have a config file (yaml, json, custom format, etc.) that the tool knows how to interpret, and which can be kept in LastPass maybe.

These are a few possibilities (there are probably more):
1. Command line args for every variable -> This can get really long, the tool wants to be simple
1. One command line arg for the path to the config file
1. Have a convention for the config/secrets file path (like ~/.vimrc) so that you don't have to specify it every time

**Comment by jutkko** [comment]
Hey @vlad-stoian thanks for your suggestions! I had thoughts about your approach and I am now working on option 3. Stay tuned! Something very similar to `concourse fly -t` / `bosh target` command is coming.

**Comment by jutkko** [comment]
@vlad-stoian see the updated README! The information is indeed stored in `$HOME/.copy-pastarc`. Thanks for your comment!
